# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Cache Qt Linux Desktop
        id: cache-qt-linux-desktop
        uses: actions/cache@v1
        with:
          path: '${{ github.workspace }}/output/linux-desktop/'
          key: ${{ runner.os }}-QtCache-Linux-Desktop

      - name: Cache Qt Linux Android
        id: cache-qt-android
        uses: actions/cache@v1
        with:
          path: '${{ github.workspace }}/output/android/'
          key: ${{ runner.os }}-QtCache-Android

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install Qt Linux Desktop
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.9'
          host: 'linux'
          target: 'desktop'
          modules: 'qtcharts debug_info'
          dir: '${{ github.workspace }}/output/linux-desktop/'
          cached: ${{ steps.cache-qt-linux-desktop.outputs.cache-hit }}
      
      - name: Compile Linux Desktop
        run: cd src; qmake; make -j4
        
      - name: Archive linux-desktop binary
        uses: actions/upload-artifact@v2
        with:
          name: linux-desktop-binary
          path: src/qdomyos-zwift

      - uses: actions/checkout@v2
        with:
          repository: nttld/setup-ndk
          path: setup-ndk
      # The packages.json in nttld/setup-ndk has already been updated,
      # https://github.com/nttld/setup-ndk/commit/831db5b02a0f0cab80614619efe461a3dcc140e6
      # but `dist/*` has not been rebuilt yet. Build it.
      # https://github.com/nttld/setup-ndk/tree/main/dist
      - name: Locally rebuilt setup-ndk
        run: |
          npm -prefix ./setup-ndk install
          npm -prefix ./setup-ndk run all
      # Install using locally rebuilt setup-ndk
      - name: Setup Android NDK r21d
        uses: ./setup-ndk
      #- uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21d

# waiting github.com/jurplel/install-qt-action/issues/63
      - name: Install Qt Android
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.9'
          host: 'linux'
          target: 'android'
          arch: 'android_armv7'
          modules: 'qtcharts debug_info'
          dir: '${{ github.workspace }}/output/android/'
          cached: ${{ steps.cache-qt-android.outputs.cache-hit }}
      
      - name: Compile Android
        run: cd src; qmake; make -j4

#      - name: Install Qt MacOS
#        uses: jurplel/install-qt-action@v2
#        with:
#          version: '5.12.9'
#          host: 'mac'
#          target: 'desktop'
#          modules: 'qtcharts debug_info'
#          dir: '${{ github.workspace }}/output/macos/'
      
#      - name: Compile MacOS
#        run: cd src; qmake; make -j4
